function(include_compontents)
	  include_directories(./)
    foreach(compontent ${COMPONENT_PATHS})
		include_directories(${compontent})
    endforeach()
endfunction()

function(include_3rds)
    foreach(3rd_path ${COMPONENT_3RD_PATHS})
		include_directories(${3rd_path})
    endforeach()
endfunction()

function(include_all)
    include_compontents()
    include_3rds()
endfunction()
